sonar.projectKey=devops-e2e-python-pipeline
sonar.projectName=DevOps E2E Python Pipeline
sonar.sources=services/api/src,services/worker
sonar.tests=services/api/tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=reports/coverage.xml
sonar.exclusions=**/__pycache__/**,**/tests/**
